# Site settings
title: DALI 2018 - Data, Learning and Inference
permalink: "/:title.html"
# Include image banner file name below
banner: pvw.i8.png
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: dali

baseurl: "/dali2017" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting
author:
  name: DALI
  
ghub:
  edit: true
  repository: dali2017

# Registration fees and URL go here.
registration:
  fee:
    academic: 400 euros
    industry: 500 euros
  url:

# Hotel booking URL goes here
booking:
  url:
  
conference:
  draft: true
  hide_tentative: true
  instance: 4th
  name: Data Learning and Inference
  short_name: DALI
  full_name: Data Learning and Inference
  venue: H10 Rubicón Palace
  location: Playa Blanca, Lanzarote, Canary Islands
  year: 2018
  dates:
  - 2018-04-03
  - 2018-04-04
  - 2018-04-05
  hosts:
  general:
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - given: Bernhard
    family: Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon
  workshop:
  - given: Sebastian
    family: Nowozin
    institute: Microsoft Research Cambridge
    url: "http://www.nowozin.net/sebastian/"
  symposium:
  - given: Fernando
    family: Perez-Cruz
    url: "http://www.tsc.uc3m.es/~fernando"
    institute: "Swiss Data Science Center"
  - given: Isabel
    family: Valera
    url: "https://ivaleram.github.io/"
    institute: "MPI for Intelligent Systems (Tübingen)"
  assistants:
  - given: Diana
    familY: Rebmann 
    url: "https://ei.is.tuebingen.mpg.de/person/drebmann"
    institute: MPI for Intelligent Systems (Tübingen)
  steering:
  - given: Zoubin
    family: Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge and Uber
  - given: Thomas
    family: Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: Amazon and University of Sheffield
  - given: Bernhard
    family: Schölkopf
    position: Chair
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen)
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
previous_meeting:
  name: DALI 2017
  url: "http://dalimeeting.org/dali2017/"
baseurl: "/dali2018/" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
ghub:
  edit: true
  repository: dali2018
future: true

# Build settings
markdown: kramdown
